version: '3.7'

services:
  database:
    container_name: postgres-server
    restart: always
    image: postgres:latest
    volumes:
      - ./initilization/DBBookstore.sql:/docker-entrypoint-initdb.d/DBBookstore.sql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=nhuttmt
      - POSTGRES_DB=bookstore
    # networks:
    #   - 

  server:
    container_name: golang-server
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - database
    # networks:
    #   - 
volumes:
  dbinit:

# networks:
  